config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products do
    resources :prices
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :product

  def label_function
    "#{currency}#{value}"
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :prices
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = current_user.products
  end

  def new
    @product = Product.new(user: current_user)
  end

  def create
    product = Product.new(product_params)
    product.user_id = current_user.id
    if product.save
      redirect_to products_path
    else
      render 'products/new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
    product = Product.find(params[:id])
    redirect_to products_path if product.destroy
  end

  private

  def product_params
    params.require(:product).permit(:name, :size, :price_ids)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductManagementTool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container py-4">
  <h1>The product management tool homepage</h1>
  <p>...to be designed...</p>

  <%= link_to 'See my products', products_path %>
</div>

app/views/products/index.html.erb
<div class="container py-4">
  <div style='margin:16px'>
    <h1 style='color:darkslategrey; text-decoration:underline; margin-bottom:48px'>All my products</h1>

    <%= link_to 'Add a product',  new_product_path, class: 'default-button' %>
  </div>

  <table class="mt-4">
    <tr>
      <th>Product name</th>
      <th>Size</th>
    </tr>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.size %></td>
        <td class="edit-column"><%= link_to 'Edit', edit_product_path(product) %></td>
        <td class="edit-column"><%= link_to 'Delete', product_path(product), method: :delete, remote: true %></td>
      </tr>
    <% end %>

  </table>
</div>

app/views/products/new.html.erb
<div class="container py-4">
  <%= simple_form_for @product do |f| %>
    <%= f.input :name %>
    <%= f.input :size %>
    <%= f.association :prices, as: :check_boxes, label_method: :label_function, value_method: :id %>
    <%= f.button :submit, class:'default-button' %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "book.jpeg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "w.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Admin panel", "/admin", class: "dropdown-item" %>
            <%= link_to "Add a product", "/products/new", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>